version: "3"
services:
  apache:
    image: 'bitnami/apache:latest'
    ports:
    # change the port if you want
      - '1011:8080'
    volumes:
      - ./html:/app
  node:
    image: "node:8"
    user: "node"
    restart: always
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - TZ=Europe/Amsterdam
    volumes:
      - ./server:/home/node/app
    expose:
    # change the port if you want
      - "1010"
    ports:
      - 1010:3000
    command: "npm start"