//This is the storage for the quizzes and the questions with answers
module.exports = {
    quizData,
  }
  
  function quizData() {
      const data = {
         Geography: {
            1: {
               question: "What is the capital of Turkey?",
               a: "Ankara",
               b: "Istanbul",
               c: "Antalya",
               d: "Samsun",
               correct: "a",
            },
            2: {
               question: "How many continents are there?",
               a: "3",
               b: "9",
               c: "4",
               d: "7",
               correct: "d",
            },
            3: {
               question: "Which is the largest desert on earth?",
               a: "Arabian",
               b: "Arctic",
               c: "Sahara",
               d: "Puntland",
               correct: "c",
            },
            4: {
               question: "What is a very cold part of Russia?",
               a: "Antarctica",
               b: "North Ice",
               c: "Siberia",
               d: "Rogers Pass",
               correct: "c",
            },
            5: {
               question: "What is the noisiest city in the world?",
               a: "Barcelona",
               b: "Hong Kong",
               c: "Mumbai",
               d: "Cairo",
               correct: "b",
            },
            6: {
               question: "What is the national animal of China?",
               a: "Gian panda",
               b: "Red-crowned crane",
               c: "Chinese dragon",
               d: "Golden Pheasant",
               correct: "a",
            },
            7: {
               question: "In which country is Krakow located?",
               a: "Russia",
               b: "Poland",
               c: "Ukraine",
               d: "Romania",
               correct: "b",
            },
            8: {
               question: "How many time zones are there in the world?",
               a: "3",
               b: "6",
               c: "12",
               d: "24",
               correct: "d",
            },
         },
         History: {
            1: {
               question: "Who was the first president of the USA?",
               a: "Thomas Jefferson",
               b: "James Madison",
               c: "George Washington",
               d: "John Adams",
               correct: "c",
            },
            2: {
               question: "In which city was the Titanic built?",
               a: "Belfast",
               b: "Holywood",
               c: "Greenisland",
               d: "Whitehead",
               correct: "a",
            },
            3: {
               question: "Who discovered Greenland?",
               a: "Erik the Red",
               b: "Juan Fernandez",
               c: "Willem Dampier",
               d: "Alexander the Great",
               correct: "a",
            },
            4: {
               question: "What was the former name of New York?",
               a: "New Dubai",
               b: "New Delhi",
               c: "New Berlin",
               d: "New Amsterdam",
               correct: "d",
            },
            5: {
               question: "On which island was Napoleon born?",
               a: "Capri",
               b: "Corsica",
               c: "Bali",
               d: "Santorini",
               correct: "b",
            },
            6: {
               question: "Which city was the capital of Australia from 1901 to 1927?",
               a: "Sydney",
               b: "Melbourne",
               c: "Perth",
               d: "Hobart",
               correct: "b",
            },
            7: {
               question: "Who was the first king of Belgium?",
               a: "Leopold II",
               b: "Albert I",
               c: "Leopold I",
               d: "Baudouin",
               correct: "c",
            },
         },
         Language: {
            1: {
               question: "What does the abbreviation SMS mean?",
               a: "Short Message Service",
               b: "Small Message Services",
               c: "Short Message Services",
               d: "Small Message Service",
               correct: "a",
            },
            2: {
               question: "What does the abbreviation GPS mean?",
               a: "Global Positioning Solution",
               b: "Great Positioning Solution",
               c: "Global Position System",
               d: "Global Positioning System",
               correct: "d",
            },
            3: {
               question: "What is the singular of Scampi?",
               a: "Scamp",
               b: "Scampo",
               c: "Scampa",
               d: "Scampit",
               correct: "b",
            },
            4: {
               question: "What is the most spoken language in the world?",
               a: "Deutsch",
               b: "Dutch",
               c: "Chinese",
               d: "English",
               correct: "c",
            },
            5: {
               question: "What do you call a motorcycle with four wheels?",
               a: "Quad",
               b: "Cruiser",
               c: "Off-road",
               d: "Moped",
               correct: "a",
            },
            6: {
               question: "Which weekday is domingo in Spanish and dimanche in French?",
               a: "Thursday",
               b: "Friday",
               c: "Saturday",
               d: "Sunday",
               correct: "d",
            },
            7: {
               question: "What is the meaning of the Arab word Habibi?",
               a: "Asshole",
               b: "Sweetheart",
               c: "Baby",
               d: "Friend",
               correct: "b",
            },
         },
         Film: {
            1: {
               question: "How many oscars did the Titanic movie got?",
               a: "5",
               b: "11",
               c: "14",
               d: "9",
               correct: "b",
            },
            2: {
               question: "How many Tomb Raider movies were made?",
               a: "1",
               b: "2",
               c: "3",
               d: "4",
               correct: "b",
            },
            3: {
               question: "What number is on Herbie the beatle?",
               a: "51",
               b: "52",
               c: "53",
               d: "54",
               correct: "c",
            },
            4: {
               question: "Which malformation did Marilyn Monroe have when she was born?",
               a: "One blind eye",
               b: "One leg",
               c: "Twelve fingers",
               d: "Six toes",
               correct: "d",
            },
            5: {
               question: "Who was the leading actress in Sister act I en II ?",
               a: "Whoopi Goldberg",
               b: "Wendy Makkena",
               c: "Maggie Smith",
               d: "Kathy Najimy",
               correct: "a",
            },
            6: {
               question: "What is the name of the bald commander of the Enterprise in Star Trek?",
               a: "Captain Alien",
               b: "Dr. Jeremy Lucas",
               c: "Captain Picard",
               d: "Com Officer",
               correct: "c",
            },
            7: {
               question: "Who is the director of the X-files?",
               a: "Rob Bouwman",
               b: "Rob Bowman",
               c: "Ralf Bowman",
               d: "Harry Bouwman",
               correct: "b",
            },
            8: {
               question: "What is the house number of the Simpsons?",
               a: "742",
               b: "743",
               c: "750",
               d: "769",
               correct: "a",
            },
         },
         Culture: {
            1: {
               question: "What color are often the domes of churches in Russia?",
               a: "White",
               b: "Silver",
               c: "Gold",
               d: "Brown",
               correct: "c",
            },
            2: {
               question: "What is the first book of the Old Testament?",
               a: "Levitics",
               b: "Genesis",
               c: "Exodus",
               d: "Deuteronomy",
               correct: "b",
            },
            3: {
               question: "Who did the Mona Lisa paint?",
               a: "Vincent van Gogh",
               b: "Rembrandt",
               c: "Artemisia Gentileschi",
               d: "Leonardo Da Vinci",
               correct: "d",
            },
            4: {
               question: "In which English town did Adolf Hitler study art?",
               a: "Langport",
               b: "Liverpool",
               c: "Leyton",
               d: "Leiston",
               correct: "b",
            },
            5: {
               question: "In which country was the famous painter El Greco born?",
               a: "Greece",
               b: "Guatemala",
               c: "Luxembourg",
               d: "Micronesia",
               correct: "a",
            },
            6: {
               question: "In which city did Romeo and Julia live?",
               a: "Milan",
               b: "Florence",
               c: "Verona",
               d: "Venice",
               correct: "c",
            },
            7: {
               question: "In which city is the famous Manneken Pis fountain?",
               a: "Amsterdam",
               b: "Brussels",
               c: "Berlin",
               d: "Barcelona",
               correct: "b",
            },
         },
      }
      return data;
   }
